check if mosquitto_sub and mosquitto_pub are installed when run cmd

diff --git a/home_bin/mqttpub_test b/home_bin/mqttpub_test
--- a/home_bin/mqttpub_test
+++ b/home_bin/mqttpub_test
@@ -9,6 +9,20 @@ function usage()
     exit 0
 }
 
+function cmd_exists ()
+{
+    if ! type $1> /dev/null 2>&1; then
+        return 1
+    else
+        return 0
+    fi
+}
+
+if ! cmd_exists mosquitto_pub ; then
+    echo "mosquitto_pub not found"
+    exit 0
+fi
+
 SERVER=localhost
 TOPIC="hellomqtt/topic"
 PAYLOAD="Hello"
